### ISSUE TITLE
Histogram bars need to be outlined when no subset is chosen

### ISSUE THREAD

**Issue by patudom** [cosmicds/solar-eclipse-2024#102]
- [x] When there is no subset selected, the histogram bars for the "main" dataset need to be outlined. I didn't see the white bar at all. (I'm assuming this is an unintended consequence of removing the outline from the gray bars when a subset is chosen).

<img width="1432" alt="Screenshot 2024-03-14 at 3 25 55 PM" src="https://github.com/cosmicds/solar-eclipse-2024/assets/12750048/60e615d6-0dfb-4bd8-a607-ad56a4c13982">

_Originally posted by @patudom in https://github.com/cosmicds/solar-eclipse-2024/issues/97#issuecomment-1998542790_

**Comment by johnarban** [comment]
address in #93
