### ISSUE TITLE
Check altitude of moon before setting initial view

### ISSUE THREAD

**Issue by patudom** [cosmicds/solar-eclipse-2024#12]
The opening view for the DS uses the dark moon sprite instead of the correct blue sprite. As soon as you change time, it correctly sets itself to the blue sprite.

@johnarban was helping me diagnose this, and we saw that the initial altitude for the moon is set to be below the horizon (at  -0.3253001458260219 rad). We need to initialize wwt to use the correct starting lat/long before it grabs the moon position.

**Comment by johnarban** [comment]
After a bit more looking, it appears the the Moons ra/dec aren't updating by the time it gets called. I tried a moving it around and delaying updatemoontexture get called, but it seemed to just not work.

**Comment by Carifio24** [comment]
This is resolved by #24.
