### ISSUE TITLE
Evaluation plans

### ISSUE THREAD

**Issue by patudom** [cosmicds/solar-eclipse-2024#51]
- Can we distinguish between locations selected within the location picker tab vs. the cloud cover tab?
- Can we count how many people are going to the book and to the i tab?
- We could do an overall count for total # of people who pressed each button vs. person A clicked on buttons 1, 2, 5, person B clicked on buttons 2, 5, 6, etc. Make sure we don't double count people who click the book more than once, etc.

(how many things did they actually do relative to how many things were available to the to do)

**Comment by patudom** [comment]
We met today to discuss the eval plans with Sue, and this is what she requests that we store for users who don't opt out:

- [ ] Count and list of lat/long for locations selected from the default view
- [ ] Count and list of lat/long for locations selected from the cloud data view
- [ ] If user opened the information book and how long it was opened for.
- [ ] If possible, how long the app was used overall. (If this is not easy to track, we can just get the averages from the analytics data.

**Comment by Carifio24** [comment]
@patudom Is this all set with #78? Or were there more things that we wanted to add?

**Comment by patudom** [comment]
Should be all set once #115 is merged.
