### ISSUE TITLE
Add a query parameter for development to not display splash screens

### ISSUE THREAD

**Issue by patudom** [cosmicds/solar-eclipse-2024#67]
This is actually an issue for all the vue-based Data Stories, not just the solar eclipse. @Carifio24, we often turn off the splash screen for convenience during development, but then we forget to turn it back on before we merge and deploy a branch.

Is there a way to make `showSplashScreen` a query parameter that we can set to false during development, but remains true on the branch so we don't have to remember to reset it on the deployed version?

**Comment by Carifio24** [comment]
Sure! I can take care of that
