### ISSUE TITLE
Improved Advanced Weather Data Loading

### ISSUE THREAD

**Issue by patudom** [cosmicds/solar-eclipse-2024#86]
- [x] Strip lat/long columns into its own file that can be used and remove from the individual year files
- [ ] Test if it feels better to load everything at once or if it's ok to load data on demand
- [ ] Test if we can compress/decompress client-side
- [ ] For later - add a query parameter to make the advanced data view visible in the deployed version so we can test how the data loads in the deployed app
- [ ] Check if it's faster to not recreate the cloud layer grid every time and instead update their colors. If not,  do a quick test to see if canvas vs. svg rendering is faster (https://leafletjs.com/reference.html#canvas)
- [ ] If the opacity of a cloud square is low enough that the square is not visible to the eye anyway, just don't draw it.

**Comment by Carifio24** [comment]
Compressing data files and decompressing client-side is addressed in #109.

**Comment by patudom** [comment]
Other tasks are addressed in #119 and it is very fast now thanks to @Jack-Hayes!
