### ISSUE TITLE
Onscreen text in the top map box is not highlightable (so cannot be copy/pasted). Do we want it to be that way?

### ISSUE THREAD

**Issue by patudom** [cosmicds/solar-eclipse-2024#98]

**Comment by Carifio24** [comment]
I don't know what we want the behavior to be, but just wanted to note that currently the text selection is explicitly disabled in the ruleset for `#guided-content-container` [here](https://github.com/cosmicds/solar-eclipse-2024/blob/main/src/SolarEclipse2024.vue#L4762).

**Comment by patudom** [comment]
in `description` class css add `user-select: auto;`
